# Generated by Django 5.1.2 on 2024-10-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_carouselitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='countries/')),
                ('flag_image', models.ImageField(upload_to='flags/')),
            ],
        ),
    ]
