# Generated by Django 5.1.2 on 2024-10-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
